services:
  mongodb:
    extends:
      file: ./bigdata-communes/docker/mongo-compose.yml
      service: mongodb

  namenode:
    extends:
      file: ./bigdata-communes/docker/hdfs-compose.yml
      service: namenode

  datanode:
    extends:
      file: ./bigdata-communes/docker/hdfs-compose.yml
      service: datanode

  datanode1:
    extends:
      file: ./bigdata-communes/docker/hdfs-compose.yml
      service: datanode1

  datanode2:
    extends:
      file: ./bigdata-communes/docker/hdfs-compose.yml
      service: datanode2

  spark-master:
    extends:
      file: ./bigdata-communes/docker/spark-compose.yml
      service: spark-master

  spark-worker-1:
    extends:
      file: ./bigdata-communes/docker/spark-compose.yml
      service: spark-worker-1

  spark-worker-2:
    extends:
      file: ./bigdata-communes/docker/spark-compose.yml
      service: spark-worker-2

  review-generator:
    extends:
      file: ./bigdata-communes/docker/review-generator.yml
      service: review-generator
      
networks:
  hadoop:

volumes:
  namenode:
  datanode:
  datanode1:
  datanode2:
  mongo_data:
