services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - hadoop
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
