services:
  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    command: ["/bin/bash", "./scripts/start-master.sh"]
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ../spark:/scripts
    networks:
      - hadoop

  spark-worker-1:
    image: apache/spark:latest
    container_name: spark-worker-1
    command: ["/bin/bash", "-c", "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"]
    depends_on:
      - spark-master
    networks:
      - hadoop

  spark-worker-2:
    image: apache/spark:latest
    container_name: spark-worker-2
    command: ["/bin/bash", "-c", "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"]
    depends_on:
      - spark-master
    networks:
      - hadoop

networks:
  hadoop:
